[platformio]
default_envs = xiao_nrf54l15

[env]
platform = symlink://../../..
framework = arduino
monitor_speed = 115200
board_build.clean_ble = on

[env:xiao_nrf54l15]
board = xiao_nrf54l15

[env:xiao_nrf54lm20a]
board = xiao_nrf54lm20b
